#DB
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:./data/sampledata
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console