server:
  port: 8090


springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.son

#liquibase
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
